//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace last_supermarket_asmaa.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodcuct
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Notes { get; set; }
        
    }
}
